apiVersion: v2
name: zootr
description: Helm chart for zootr-tracker
type: application
###! Manually update when ONLY updating chart/subcharts/chart dependencies
###! Otherwise it is updated in ci when appVersion gets an update
###! We _shouldnt_ "release" (triggering version updates) for only chart updates
###! TODO: Somehow add safeguard to not update chart version in ci if manually updated
version: 0.4.0
###! Follows the version in docker-compose.yml
###! Updated in CI and should not need manual updates
appVersion: "0.5.0"
## Cannot share data between dependency charts using 'import-values'
## Data imported only available to manifests in this charts templates/ folder
dependencies:
- name: tpl
  version: 0.9.3
  alias: app
  condition: app.enabled
  repository: https://gitlab.codeopensrc.com/api/v4/projects/36/packages/helm/stable
- name: tpl
  version: 0.9.3
  alias: db
  condition: db.enabled
  repository: https://gitlab.codeopensrc.com/api/v4/projects/36/packages/helm/stable
