.enable_db: &enable_db false

app:
  enabled: true
  replicaCount: 1
  image:
    repository: registry.codeopensrc.com/os/zootr-tracker/app
    tag: 0.2.0
  secretStringData:
    MONGO_DB_NAME: "zootr"
    SAMPLE_SECRET: "SAMPLE_SECRET_ENV_VAR"
  configMapData:
    DEV_DATABASE_URL_ORIGIN: "mongodb://zootr-db:27017"
    ENABLE_DB:               *enable_db
db:
  enabled: *enable_db
